province=[(1, 'AG', 'Agrigento'),
(2, 'AL', 'Alessandria'),
(3, 'AN', 'Ancona'),
(4, 'AQ', 'L`Aquila'),
(5, 'AR', 'Arezzo'),
(6, 'AP', 'Ascoli Piceno'),
(7, 'AT', 'Asti'),
(8, 'AV', 'Avellino'),
(9, 'BA', 'Bari'),
(10, 'BT', 'Barletta-Andria-Trani'),
(11, 'BL', 'Belluno'),
(12, 'BN', 'Benevento'),
(13, 'BG', 'Bergamo'),
(14, 'BI', 'Biella'),
(15, 'BO', 'Bologna'),
(16, 'BZ', 'Bolzano'),
(17, 'BS', 'Brescia'),
(18, 'BR', 'Brindisi'),
(19, 'CA', 'Cagliari'),
(20, 'CL', 'Caltanissetta'),
(21, 'CB', 'Campobasso'),
(22, 'CI', 'Carbonia - Iglesias'),
(23, 'CE', 'Caserta'),
(24, 'CT', 'Catania'),
(25, 'CZ', 'Catanzaro'),
(26, 'CH', 'Chieti'),
(27, 'CO', 'Como'),
(28, 'CS', 'Cosenza'),
(29, 'CR', 'Cremona'),
(30, 'KR', 'Crotone'),
(31, 'CN', 'Cuneo'),
(32, 'EN', 'Enna'),
(33, 'FM', 'Fermo'),
(34, 'FE', 'Ferrara'),
(35, 'FI', 'Firenze'),
(36, 'FG', 'Foggia'),
(37, 'FC', 'Forli-Cesena'),
(38, 'FR', 'Frosinone'),
(39, 'GE', 'Genova'),
(40, 'GO', 'Gorizia'),
(41, 'GR', 'Grosseto'),
(42, 'IM', 'Imperia'),
(43, 'IS', 'Isernia'),
(44, 'LT', 'Latina'),
(45, 'LE', 'Lecce'),
(46, 'LC', 'Lecco'),
(47, 'LI', 'Livorno'),
(48, 'LO', 'Lodi'),
(49, 'LU', 'Lucca'),
(50, 'MC', 'Macerata'),
(51, 'MN', 'Mantova'),
(52, 'MS', 'Massa-Carrara'),
(53, 'MT', 'Matera'),
(54, 'VS', 'Medio Campidano'),
(55, 'ME', 'Messina'),
(56, 'MI', 'Milano'),
(57, 'MO', 'Modena'),
(58, 'MB', 'Monza e della Brianza'),
(59, 'NA', 'Napoli'),
(60, 'NO', 'Novara'),
(61, 'NU', 'Nuoro'),
(62, 'OG', 'Ogliastra'),
(63, 'OT', 'Olbia - Tempio'),
(64, 'OR', 'Oristano'),
(65, 'PD', 'Padova'),
(66, 'PA', 'Palermo'),
(67, 'PR', 'Parma'),
(68, 'PV', 'Pavia'),
(69, 'PG', 'Perugia'),
(70, 'PU', 'Pesaro e Urbino'),
(71, 'PE', 'Pescara'),
(72, 'PC', 'Piacenza'),
(73, 'PI', 'Pisa'),
(74, 'PT', 'Pistoia'),
(75, 'PN', 'Pordenone'),
(76, 'PZ', 'Potenza'),
(77, 'PO', 'Prato'),
(78, 'RG', 'Ragusa'),
(79, 'RA', 'Ravenna'),
(80, 'RC', 'REGGIO DI CALABRIA'),
(81, 'RE', 'Reggio nell`Emilia'),
(82, 'RI', 'Rieti'),
(83, 'RN', 'Rimini'),
(84, 'RM', 'Roma'),
(85, 'RO', 'Rovigo'),
(86, 'SA', 'Salerno'),
(87, 'SS', 'Sassari'),
(88, 'SV', 'Savona'),
(89, 'SI', 'Siena'),
(90, 'SR', 'Siracusa'),
(91, 'SO', 'Sondrio'),
(92, 'SP', 'LA Spezia'),
(93, 'TA', 'Taranto'),
(94, 'TE', 'Teramo'),
(95, 'TR', 'Terni'),
(96, 'TO', 'Torino'),
(97, 'TP', 'Trapani'),
(98, 'TN', 'Trento'),
(99, 'TV', 'Treviso'),
(100, 'TS', 'Trieste'),
(101, 'UD', 'Udine'),
(102, 'VA', 'Varese'),
(103, 'VE', 'Venezia'),
(104, 'VB', 'Verbano Cusio Ossola'),
(105, 'VC', 'Vercelli'),
(106, 'VR', 'Verona'),
(107, 'VV', 'Vibo Valentia'),
(108, 'VI', 'Vicenza'),
(109, 'VT', 'Viterbo'),
(110, 'AO', 'Aosta')]
