# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/giuseppe/Projects/GIS/plugin/mmasgis/anagrafica.ui'
#
# Created: Sat Nov 12 18:05:51 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(QtGui.QMainWindow):
	def __init__(self, parent = None):
	    """
	        Constructor
	    """
	    QtGui.QMainWindow.__init__(self)
	    self.setupUi(self)
	    
	    
	def setupUi(self, MainWindow):
	    MainWindow.setObjectName(_fromUtf8("MainWindow"))
            MainWindow.resize(1132, 692)
            MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
            self.centralwidget = QtGui.QWidget(MainWindow)
            self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
            self.gridLayout = QtGui.QGridLayout(self.centralwidget)
            self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
            self.label = QtGui.QLabel(self.centralwidget)
            self.label.setText(QtGui.QApplication.translate("MainWindow", "Codice MMas", None, QtGui.QApplication.UnicodeUTF8))
            self.label.setObjectName(_fromUtf8("label"))
            self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
            self.text_codice_mmas = QtGui.QLineEdit(self.centralwidget)
            self.text_codice_mmas.setObjectName(_fromUtf8("text_codice_mmas"))
            self.gridLayout.addWidget(self.text_codice_mmas, 0, 1, 1, 2)
            self.checkBox_cliente = QtGui.QCheckBox(self.centralwidget)
            self.checkBox_cliente.setText(QtGui.QApplication.translate("MainWindow", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
            self.checkBox_cliente.setObjectName(_fromUtf8("checkBox_cliente"))
            self.gridLayout.addWidget(self.checkBox_cliente, 0, 3, 1, 1)
            self.label_4 = QtGui.QLabel(self.centralwidget)
            self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Ragione sociale", None, QtGui.QApplication.UnicodeUTF8))
            self.label_4.setObjectName(_fromUtf8("label_4"))
            self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
            self.text_ragione_sociale = QtGui.QLineEdit(self.centralwidget)
            self.text_ragione_sociale.setObjectName(_fromUtf8("text_ragione_sociale"))
            self.gridLayout.addWidget(self.text_ragione_sociale, 2, 1, 1, 2)
            self.label_5 = QtGui.QLabel(self.centralwidget)
            self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Titolare", None, QtGui.QApplication.UnicodeUTF8))
            self.label_5.setObjectName(_fromUtf8("label_5"))
            self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
            self.text_titolare = QtGui.QLineEdit(self.centralwidget)
            self.text_titolare.setObjectName(_fromUtf8("text_titolare"))
            self.gridLayout.addWidget(self.text_titolare, 3, 1, 1, 2)
            self.label_7 = QtGui.QLabel(self.centralwidget)
            self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Indirizzo", None, QtGui.QApplication.UnicodeUTF8))
            self.label_7.setObjectName(_fromUtf8("label_7"))
            self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
            self.text_indirizzo = QtGui.QLineEdit(self.centralwidget)
            self.text_indirizzo.setObjectName(_fromUtf8("text_indirizzo"))
            self.gridLayout.addWidget(self.text_indirizzo, 4, 1, 1, 3)
            self.label_8 = QtGui.QLabel(self.centralwidget)
            self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Comune", None, QtGui.QApplication.UnicodeUTF8))
            self.label_8.setObjectName(_fromUtf8("label_8"))
            self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
            self.text_comune = QtGui.QLineEdit(self.centralwidget)
            self.text_comune.setObjectName(_fromUtf8("text_comune"))
            self.gridLayout.addWidget(self.text_comune, 8, 1, 1, 2)
            self.label_11 = QtGui.QLabel(self.centralwidget)
            self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Telefono", None, QtGui.QApplication.UnicodeUTF8))
            self.label_11.setObjectName(_fromUtf8("label_11"))
            self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
            self.text_telefono = QtGui.QLineEdit(self.centralwidget)
            self.text_telefono.setObjectName(_fromUtf8("text_telefono"))
            self.gridLayout.addWidget(self.text_telefono, 9, 1, 1, 2)
            self.lineEdit_13 = QtGui.QLineEdit(self.centralwidget)
            self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
            self.gridLayout.addWidget(self.lineEdit_13, 9, 4, 1, 3)
            self.label_13 = QtGui.QLabel(self.centralwidget)
            self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
            self.label_13.setObjectName(_fromUtf8("label_13"))
            self.gridLayout.addWidget(self.label_13, 10, 0, 1, 1)
            self.text_mail = QtGui.QLineEdit(self.centralwidget)
            self.text_mail.setObjectName(_fromUtf8("text_mail"))
            self.gridLayout.addWidget(self.text_mail, 10, 1, 1, 2)
            self.label_17 = QtGui.QLabel(self.centralwidget)
            self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Origine", None, QtGui.QApplication.UnicodeUTF8))
            self.label_17.setObjectName(_fromUtf8("label_17"))
            self.gridLayout.addWidget(self.label_17, 12, 7, 1, 2)
            self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
            self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Anagrafica centrificata", None, QtGui.QApplication.UnicodeUTF8))
            self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
            self.gridLayout.addWidget(self.checkBox_2, 13, 0, 1, 2)
            self.label_16 = QtGui.QLabel(self.centralwidget)
            self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Data aggiornamento", None, QtGui.QApplication.UnicodeUTF8))
            self.label_16.setObjectName(_fromUtf8("label_16"))
            self.gridLayout.addWidget(self.label_16, 13, 2, 1, 2)
            self.date_aggiornamento = QtGui.QDateEdit(self.centralwidget)
            self.date_aggiornamento.setMaximumSize(QtCore.QSize(100, 16777215))
            self.date_aggiornamento.setObjectName(_fromUtf8("date_aggiornamento"))
            self.gridLayout.addWidget(self.date_aggiornamento, 13, 4, 1, 3)
            self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
            self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "MMASGIS", None, QtGui.QApplication.UnicodeUTF8))
            self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
            self.gridLayout.addWidget(self.checkBox_3, 13, 7, 1, 2)
            self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
            self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Altro", None, QtGui.QApplication.UnicodeUTF8))
            self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
            self.gridLayout.addWidget(self.checkBox_4, 13, 9, 1, 1)
            self.tab_2 = QtGui.QTabWidget(self.centralwidget)
            self.tab_2.setObjectName(_fromUtf8("tab_2"))
            self.tab = QtGui.QWidget()
            self.tab.setObjectName(_fromUtf8("tab"))
            self.gridLayout_2 = QtGui.QGridLayout(self.tab)
            self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
            self.table_parametri_mmas = QtGui.QTableWidget(self.tab)
            self.table_parametri_mmas.setObjectName(_fromUtf8("table_parametri_mmas"))
            self.table_parametri_mmas.setColumnCount(0)
            self.table_parametri_mmas.setRowCount(0)
            self.gridLayout_2.addWidget(self.table_parametri_mmas, 0, 0, 1, 1)
            self.tab_2.addTab(self.tab, _fromUtf8(""))
            self.Marchi = QtGui.QWidget()
            self.Marchi.setObjectName(_fromUtf8("Marchi"))
            self.gridLayout_3 = QtGui.QGridLayout(self.Marchi)
            self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
            self.table_marchi_mmas = QtGui.QTableWidget(self.Marchi)
            self.table_marchi_mmas.setObjectName(_fromUtf8("table_marchi_mmas"))
            self.table_marchi_mmas.setColumnCount(0)
            self.table_marchi_mmas.setRowCount(0)
            self.gridLayout_3.addWidget(self.table_marchi_mmas, 0, 0, 1, 1)
            self.tab_2.addTab(self.Marchi, _fromUtf8(""))
            self.Potenziali = QtGui.QWidget()
            self.Potenziali.setObjectName(_fromUtf8("Potenziali"))
            self.gridLayout_4 = QtGui.QGridLayout(self.Potenziali)
            self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
            self.table_potenziali_mmas = QtGui.QTableWidget(self.Potenziali)
            self.table_potenziali_mmas.setObjectName(_fromUtf8("table_potenziali_mmas"))
            self.table_potenziali_mmas.setColumnCount(0)
            self.table_potenziali_mmas.setRowCount(0)
            self.gridLayout_4.addWidget(self.table_potenziali_mmas, 0, 0, 1, 1)
            self.tab_2.addTab(self.Potenziali, _fromUtf8(""))
            self.Parametri = QtGui.QWidget()
            self.Parametri.setObjectName(_fromUtf8("Parametri"))
            self.gridLayout_5 = QtGui.QGridLayout(self.Parametri)
            self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
            self.table_parametri_territoriali = QtGui.QTableWidget(self.Parametri)
            self.table_parametri_territoriali.setObjectName(_fromUtf8("table_parametri_territoriali"))
            self.table_parametri_territoriali.setColumnCount(0)
            self.table_parametri_territoriali.setRowCount(0)
            self.gridLayout_5.addWidget(self.table_parametri_territoriali, 0, 0, 1, 1)
            self.tab_2.addTab(self.Parametri, _fromUtf8(""))
            self.Note = QtGui.QWidget()
            self.Note.setObjectName(_fromUtf8("Note"))
            self.tab_2.addTab(self.Note, _fromUtf8(""))
            self.gridLayout.addWidget(self.tab_2, 14, 0, 1, 11)
            self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
            self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 16777215))
            self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
            self.gridLayout.addWidget(self.lineEdit_10, 8, 6, 1, 1)
            self.label_6 = QtGui.QLabel(self.centralwidget)
            self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Cod. Fiscale partita iva", None, QtGui.QApplication.UnicodeUTF8))
            self.label_6.setObjectName(_fromUtf8("label_6"))
            self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
            self.text_codice_fiscale = QtGui.QLineEdit(self.centralwidget)
            self.text_codice_fiscale.setObjectName(_fromUtf8("text_codice_fiscale"))
            self.gridLayout.addWidget(self.text_codice_fiscale, 3, 4, 1, 1)
            self.label_2 = QtGui.QLabel(self.centralwidget)
            self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Codice cliente", None, QtGui.QApplication.UnicodeUTF8))
            self.label_2.setObjectName(_fromUtf8("label_2"))
            self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
            self.text_codice_cliente = QtGui.QLineEdit(self.centralwidget)
            self.text_codice_cliente.setObjectName(_fromUtf8("text_codice_cliente"))
            self.gridLayout.addWidget(self.text_codice_cliente, 1, 4, 1, 1)
            self.label_3 = QtGui.QLabel(self.centralwidget)
            self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Potenziale MMAS", None, QtGui.QApplication.UnicodeUTF8))
            self.label_3.setObjectName(_fromUtf8("label_3"))
            self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
            self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
            self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
            self.gridLayout.addWidget(self.lineEdit_3, 0, 6, 1, 1)
            self.text_provincia = QtGui.QLineEdit(self.centralwidget)
            self.text_provincia.setMaximumSize(QtCore.QSize(50, 16777215))
            self.text_provincia.setObjectName(_fromUtf8("text_provincia"))
            self.gridLayout.addWidget(self.text_provincia, 8, 4, 1, 1)
            self.label_9 = QtGui.QLabel(self.centralwidget)
            self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Provincia", None, QtGui.QApplication.UnicodeUTF8))
            self.label_9.setObjectName(_fromUtf8("label_9"))
            self.gridLayout.addWidget(self.label_9, 8, 3, 1, 1)
            self.label_10 = QtGui.QLabel(self.centralwidget)
            self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Cap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_10.setObjectName(_fromUtf8("label_10"))
            self.gridLayout.addWidget(self.label_10, 8, 5, 1, 1)
            self.label_14 = QtGui.QLabel(self.centralwidget)
            self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Sito internet", None, QtGui.QApplication.UnicodeUTF8))
            self.label_14.setObjectName(_fromUtf8("label_14"))
            self.gridLayout.addWidget(self.label_14, 12, 2, 1, 1)
            self.text_sito = QtGui.QLineEdit(self.centralwidget)
            self.text_sito.setObjectName(_fromUtf8("text_sito"))
            self.gridLayout.addWidget(self.text_sito, 12, 3, 1, 1)
            self.label_15 = QtGui.QLabel(self.centralwidget)
            self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Certificazione", None, QtGui.QApplication.UnicodeUTF8))
            self.label_15.setObjectName(_fromUtf8("label_15"))
            self.gridLayout.addWidget(self.label_15, 10, 3, 1, 1)
            self.text_certificazione = QtGui.QLineEdit(self.centralwidget)
            self.text_certificazione.setObjectName(_fromUtf8("text_certificazione"))
            self.gridLayout.addWidget(self.text_certificazione, 10, 4, 1, 1)
            self.text_fax = QtGui.QLineEdit(self.centralwidget)
            self.text_fax.setObjectName(_fromUtf8("text_fax"))
            self.gridLayout.addWidget(self.text_fax, 2, 4, 1, 1)
            self.label_12 = QtGui.QLabel(self.centralwidget)
            self.label_12.setMaximumSize(QtCore.QSize(40, 16777215))
            self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Fax", None, QtGui.QApplication.UnicodeUTF8))
            self.label_12.setObjectName(_fromUtf8("label_12"))
            self.gridLayout.addWidget(self.label_12, 2, 3, 1, 1)
            MainWindow.setCentralWidget(self.centralwidget)
            self.menubar = QtGui.QMenuBar(MainWindow)
            self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 27))
            self.menubar.setObjectName(_fromUtf8("menubar"))
            MainWindow.setMenuBar(self.menubar)
            self.statusbar = QtGui.QStatusBar(MainWindow)
            self.statusbar.setObjectName(_fromUtf8("statusbar"))
            MainWindow.setStatusBar(self.statusbar)
    
            self.retranslateUi(MainWindow)
            self.tab_2.setCurrentIndex(0)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
	    self.tab_2.setTabText(self.tab_2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Parametri MMAS", None, QtGui.QApplication.UnicodeUTF8))
	    self.tab_2.setTabText(self.tab_2.indexOf(self.Marchi), QtGui.QApplication.translate("MainWindow", "Marchi MMAS", None, QtGui.QApplication.UnicodeUTF8))
            self.tab_2.setTabText(self.tab_2.indexOf(self.Potenziali), QtGui.QApplication.translate("MainWindow", "Potenziali MMAS", None, QtGui.QApplication.UnicodeUTF8))
            self.tab_2.setTabText(self.tab_2.indexOf(self.Parametri), QtGui.QApplication.translate("MainWindow", "Parametri territoriali", None, QtGui.QApplication.UnicodeUTF8))
            self.tab_2.setTabText(self.tab_2.indexOf(self.Note), QtGui.QApplication.translate("MainWindow", "Note", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

